### PR TITLE
Feature: classic template

### PR DESCRIPTION
**Pull request by jonwaldstein**
Resolves: #42

## Description

This introduces the first template for our next-gen forms: _Classic Template_.  This is not a complete representation of our existing classic template because our form's functionality is not necessarily the same yet.  As we carry over more features & blocks like _add-on_ functionality, this template will be updated.  This PR lays more of the ground-work for building templates and gives us an _initial_ template to continue building out.

## Affects

- Our Template Api & base fields structure
- Next-Gen donation form block defaults to classic template for now
- Block render updated to match form builder persistence updates (different names for things)

## Visuals

Screen Shot 2022-07-25 at 11 31 02 AM

Screen Shot 2022-07-25 at 11 33 48 AM

## Testing Instructions

- Create a new form using the next-gen form builder
- Add a donation form block to a page
- Make sure you have either Next Gen Test Gateway or Next Gen Stripe Gateway enabled
- Viewing the form should be visually similar to our good ol' Classic Template
- Test out the Form!

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by jonwaldstein** [comment]
@kjohnson @JasonTheAdams this is ready for review.  Couple things to note:

1. The custom `AmountField` provided by this template will likely be merged into our core field.  I started building that separate so I had something tangible to use as a _template override_ introduced in this PR.
2. Things like colors are obviously not dynamic yet - that's functionality we'll need to add in the near future.
3. I just used labels instead of placeholders for our inputs. I don't think we have an option for using placeholders yet so that's something to think through.
4. There is an existing bug related to validation - where the input will lose focus after first trying to resolve an error.  It's unrelated to this PR as it's happening on develop as well - so i'll create an issue for that.

**Comment by kjohnson** [comment]
> I just used labels instead of placeholders for our inputs. I don't think we have an option for using placeholders yet so that's something to think through.

My understanding is that we are going to move forward with actual labels, as opposed to the placeholder as label direction.

**Comment by kjohnson** [comment]
> The custom AmountField provided by this template will likely be merged into our core field. I started building that separate so I had something tangible to use as a template override introduced in this PR.

Thanks for adding it this way - that helps with visualizing how that will work.

**Review by kjohnson — APPROVED** [review]
Looks good to me. It is great to see a template being registered and that showing when the block is rendered.

**Comment by kjohnson** [comment]
Knowing that you have a punch list of items that you know you want to address I'll go ahead and merge this into develop so that you can work from there and we can get the builder and the template working together in develop.

**Comment by JasonTheAdams** [comment]
I was a bit late to reviewing it, but this looks great @jonwaldstein! The only thing I noticed is that the section descriptions are missing.

**Comment by jonwaldstein** [comment]
> I was a bit late to reviewing it, but this looks great @jonwaldstein! The only thing I noticed is that the section descriptions are missing.

Section descriptions are working for me:

Screen Shot 2022-07-26 at 7 15 26 PM

**Comment by JasonTheAdams** [comment]
I mean in the template, not the Form Builder. 😊

**Comment by kjohnson** [comment]
That is a screenshot of the rendered template - not the form builder.

**Pull request merged**
