### PR TITLE
Chore: update all js packages and dependencies

### PR DESCRIPTION
**Pull request by jonwaldstein**
## Description

- Updates all JS packages and dependencies 
- uses new react 18 createRoot in form builder
- removes unnecessary react imports with automatic jsx runtime
- updates to existing styles to account for package updates
- improved hiding wp elements when viewing a form
- added notice popup when form has been updated
- lock initial sections by default when creating a form

## Affects

The build process & various styles in the builder.

## Visuals

Screenshot 2023-01-23 at 5 06 28 PM

## Testing Instructions

- Pull this down, run `npm install && npm run build`
- Make sure the form builder loads & nothing looks out of place
- Make sure a form renders on the front-end

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by jonwaldstein** [comment]
@kjohnson I got everything updated and working now.  This is the fun part of using workspaces as all the shared packages have to be in sync or else it gets confused.  Lmk if this works for you.

**Comment by jonwaldstein** [comment]
@kjohnson I noticed these upgrades also affected some of the Gutenberg styling in the form builder.  It looks like some things look nicer and there's some minor tweaks we'll have to do like the _add block_ styles.

**Comment by jonwaldstein** [comment]
@kjohnson this is ready for review now.

**Review by kjohnson — APPROVED** [review]
Looks good to me.

**Pull request merged**
