### PR TITLE
Feature: add currency setting exchange rate fraction digits

### PR DESCRIPTION
**Pull request by jonwaldstein**
## Description

This adds support for exchange rate fraction digits to display the donor.

Note: this will only affect the message displayed to the donor, not the actual donation amount.  Learn more [here](https://givewp.com/documentation/add-ons/currency-switcher/)

## Affects

Adds new exchange rate fraction digit property to the CurrencySwitcherSetting

## Visuals

Screenshot 2023-07-20 at 5 02 06 PM

Screenshot 2023-07-20 at 5 02 18 PM

## Testing Instructions

Programatically:

```
use Give\Framework\FieldsAPI\DonationForm;
use Give\Framework\FieldsAPI\Properties\DonationForm\CurrencySwitcherSetting;

add_action('givewp_donation_form_schema', static function (DonationForm $form) {
    $currencySwitcherSettings = [
        new CurrencySwitcherSetting('USD', 0, ['test-gateway', 'stripe_payment_element']),
        new CurrencySwitcherSetting('EUR', 0.911699, ['test-gateway', 'stripe_payment_element'], 6),
    ];

    $form->currencySwitcherSettings(...$currencySwitcherSettings);
    $form->currencySwitcherMessage(
        'The current exchange rate is 1.00 {base_currency} equals {new_currency_rate} {new_currency}.'
    );
});
```

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by jonwaldstein** [comment]
@glaubersilva this is ready for review.

**Review by glaubersilva — COMMENTED** [review]
@jonwaldstein Looks good to me and worked as expected. The only thing that I don't have sure is right is related to the decimal separator. In the article that you mentioned in the PR description, we can see this image: https://givewp.com/wp-content/uploads/2021/05/exchange-rates-information.png

If you pay attention to the image above, will notice that a `,` is used as a decimal separator for the Euro, but on the image attached to this PR description, the decimal separator for the Euro is a `.` like the Dolar decimal separator.

**Comment by jonwaldstein** [comment]
@glaubersilva good eye! actually what we have now is much smarter that what you are seeing on v2 forms.  We're using the donor's browser to run [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) which takes in the locale _and_ currency to determine how to format the amount.  Since my locale is `'en-US'` the format will be decimals where other locale's will display fractions that make sense to them.

**Review by glaubersilva — APPROVED** [review]
Niiice! I changed my browser to `pt_BR` and could see the `,` instead of the `.` as a decimal separator. So, this is ready for QA.

**Comment by jonwaldstein** [comment]
@glaubersilva great thanks!

**Pull request merged**
