### PR TITLE
Feature: Add Welcome Banner

### PR DESCRIPTION
**Pull request by kjohnson**
Depends on https://github.com/impress-org/givewp-gateway-server/pull/20

## Description

This PR introduces the Welcome Banner component for the NextGen feature plugin.

## Visuals

| Welcome Banner (screenshot) |
| --- |
| image |

| Dismiss Action/Animation |
| --- |
| Peek 2023-03-16 15-39 |

| Newsletter Subscribe Action/Animation |
| --- |
| Peek 2023-03-21 16-15 |

| Responsive Design |
| --- |
| Peek 2023-03-16 15-38 |

## Testing Instructions

- Dismiss the Welcome Banner using the "X"/Close at the top right.
- Reset the Welcome Banner by deleting the `givewp_next_gen_welcome_banner_dismissed` option.

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
Let's hold on merging this until I get the design system PR in place and can use that.

**Comment by kjohnson** [comment]
@jonwaldstein this is ready for review. The design system has been incorporated and the success styles have been updated.

**Comment by jonwaldstein** [comment]
@kjohnson what was decided about the "Design Mode" and "Custom Fields" images?  Looks like they are still placeholders.

**Comment by kjohnson** [comment]
@jonwaldstein updated the screenshots.

**Comment by jonwaldstein** [comment]
@kjohnson thanks, 2 things that don't necessarily have to hold this up:

1. The "Design Mode" screenshot is an outdated form design.
2. When clicking the dismiss button it took a few seconds for me until it was removed. I don't think we necessarily need to wait for the server to respond to hide the message.

**Review by jonwaldstein — APPROVED** [review]

**Pull request merged**
