### PR TITLE
Refactor: Limit sections to top level blocks

### LINKED ISSUE #21: Only allow sections at the top level (and no nested sections)
We had previously made the decision for a forced structure of sections as a top level item only. This means that only sections can be at the top level and no nested sections.

This needs to be enforced in the builder so that the form rendering does not run into any issues.

| |
|---|
| Image |

## Acceptance Criteria

-  [x] Only sections blocks are allowed as top level items
-  [x] Sections cannot be nested

### PR DESCRIPTION
**Pull request by kjohnson**
Resolves #21

## Description

This PR restricts Section blocks to top level blocks and prevents nested sections.

To do this, field blocks are injected with a list of registered section blocks to allow as parent blocks. This enforces the top level section blocks.

## Affects

Fields and Sections are now configured as an exported array and registered as blocks in the main `index.js` entry point.

## Visuals

| Sections at top level | No nested sections |
| --- | --- |
| image | image |

## Testing Instructions

- Should not see fields as top level blocks
- Should not see sections as nested blocks

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit and/or end-to-end tests
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by kjohnson** [comment]
Note: Depending on the merge order either this PR or #27 will need to be refactor to account for each other as there is a little bit of overlap in these changes.

**Comment by kjohnson** [comment]
Getting an error in the build/deploy script that I don't recognize...

```
Creating an optimized production build...
Failed to compile.
Attempted import error: '__experimentalUseDisabled' is not exported from '@wordpress/compose' (imported as 'useDisabled').
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @givewp/form-builder 
npm ERR!   at location: /home/runner/work/givewp-next-gen/givewp-next-gen/packages/form-builder 
Error: Process completed with exit code 1.
```

**Comment by jonwaldstein** [comment]
> Getting an error in the build/deploy script that I don't recognize...
> 
> ```
> Creating an optimized production build...
> Failed to compile.
> Attempted import error: '__experimentalUseDisabled' is not exported from '@wordpress/compose' (imported as 'useDisabled').
> npm ERR! Lifecycle script `build` failed with error: 
> npm ERR! Error: command failed 
> npm ERR!   in workspace: @givewp/form-builder 
> npm ERR!   at location: /home/runner/work/givewp-next-gen/givewp-next-gen/packages/form-builder 
> Error: Process completed with exit code 1.
> ```

@kjohnson I can't get past this error on my local, any ideas?

**Comment by kjohnson** [comment]
@jonwaldstein looks like WordPress made the `useDisabled` hook `stable`, which means they removed the `__experimentalUseDisabled`.

See https://github.com/WordPress/gutenberg/pull/40890/files#diff-987bccae73498d4b66ea944a556527a643bced5755b3db854b087da648b0bdfa

Looking at the dependencies we have the `@wordpress/block-editor` with an upper limit on the version, so maybe the nested dependency of `@wordpress/compose` was updated silently.

We'll need to bump the dependency version of `@wordpress/block-editor` to at least `9.4.0`.

On that note, the change was a minor version change, not a major version change, but it _was_ a breaking change for us... ugh.

**Comment by kjohnson** [comment]
@jonwaldstein specifying a version of `@wordpress/compose@5.6.0` seems to resolve the issue locally, but I'm still getting an error in the pipeline. Still looking into that.

**Comment by jonwaldstein** [comment]
@kjohnson adding the local `@wordpress/compose@5.6.0` dependency to both the form builder & plugin package.json file fixed the build & deployment issues.  I updated the develop branch so we can move along.  Thanks for looking into that 🙌

**Pull request merged**
