### PR TITLE
Refactor: v3 gateway api compatibility

### PR DESCRIPTION
**Pull request by jonwaldstein**
## Description

Depends on: https://github.com/impress-org/givewp/pull/6830

This updates gateways for v3 forms compatibility. 

- Removed the `NextGenPaymentGatewayInterface` and any check for it.  v3 forms now use the $supportedFormVersion filter `give(PaymentGatewayRegister::class)->getPaymentGateways(3)` to retrieve gateways that support v3 forms.
- Simplified `enqueueScript()` to use WordPress natively
- Renamed NextGen specific test gateways to be generic (migrating these to core)
- Both Test Gateway and Test Gateway Offsite classes have been merged into core but registering them & loading their js file here.

## Affects

- All our v3 compatible gateways

## Visuals

N/A

## Testing Instructions

Make sure you're on GiveWP https://github.com/impress-org/givewp/pull/6830 or GiveWP develop if merged

Just make sure v3 compatible gateways show up on the form properly.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by jonwaldstein** [comment]
@glaubersilva this is ready for review.

**Comment by JasonTheAdams** [comment]
@jonwaldstein @pauloiankoski `develop` is broken now that the corresponding PR in core is merged, can we prioritize this, please?

**Review by glaubersilva — CHANGES_REQUESTED** [review]
@jonwaldstein These changes are generating a fatal error because the `getLegacyFormFieldMarkup `is not present in the following file: `src/PaymentGateways/Gateways/Stripe/StripePaymentElementGateway/StripePaymentElementGateway.php`

**Comment by jonwaldstein** [comment]
@glaubersilva that interface was removed from the GiveWP core PaymentGateway class so just make sure you have the latest updates to develop and this should not be an issue.

**Review by glaubersilva — APPROVED** [review]
@jonwaldstein Ok, thanks! I updated the core and it worked as expected, so looks great to me.

**Pull request merged**
